name       : python-cssutils
version    : 1
release    : 2
source     :
    - https://pypi.python.org/packages/source/c/cssutils/cssutils-1.0.zip : 4504762f5d8800b98fa713749c00acfef8419826568f9363c490e45146a891af
license    : GPL-3.0
summary    : A CSS Cascading Style Sheets library for Python
extract    : no
description: |
    A Python package to parse and build CSS Cascading Style Sheets. DOM only, not any rendering facilities!
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
    - python3-setuptools
setup      : |
    unzip $sources/cssutils-1.0.zip
build      : |
    cd cssutils-1.0
    python setup.py build
    python3 setup.py build
install    : |
    cd cssutils-1.0
    python setup.py install --root=%installroot% --no-compile -O0
    python3 setup.py install --root=%installroot% --no-compile -O0


