name       : python-cssutils
version    : 1.0.2
release    : 6
source     :
    - https://pypi.python.org/packages/source/c/cssutils/cssutils-1.0.2.tar.gz : a2fcf06467553038e98fea9cfe36af2bf14063eb147a70958cfcaa8f5786acaf
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A CSS Cascading Style Sheets library for Python
description: |
    A Python package to parse and build CSS Cascading Style Sheets. DOM only, not any rendering facilities!
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install


